name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'breaking-change'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'minor'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'patch'
  default: patch

template: |
  ## What's Changed
  $CHANGES