name: Release Workflows Centralizados

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate next version from PR labels
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Sync Major Tag
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.release_drafter.outputs.tag_name }}
        run: |
          # Extrai o numero major da tag gerada (ex: de v1.2.3 extrai v1)
          MAJOR_TAG=$(echo "$TAG_NAME" | cut -d. -f1)

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Atualiza a tag major (ex: v1 ou v2) para apontar para o commit atual
          git tag -fa "$MAJOR_TAG" -m "Atualiza $MAJOR_TAG para a release $TAG_NAME"
          git push origin "$MAJOR_TAG" --force